# Generated by Django 4.2 on 2024-08-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('Id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ZonasHumedas',
            fields=[
                ('Id_productoZH', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Precio', models.FloatField()),
                ('Estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado')], default='Disponible', max_length=25)),
                ('Id_servicio', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('Id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('TipoPlatillo', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.FloatField()),
                ('Estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado')], default='Disponible', max_length=25)),
                ('Id_servicio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('Id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('TipoBebida', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.FloatField()),
                ('Estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado')], default='Disponible', max_length=25)),
                ('Id_servicio', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios')),
            ],
        ),
    ]
